spring:
    jackson.deserialization.fail-on-unknown-properties: true
    profiles.active: production
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
        h2:
            console:
                enabled: true
logging:
    level:
        root: info
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
server:
    port: 9090